// Enum unions mirroring the DB CHECK constraints. Arrays double as <select> options.

export const CHAMPIONSHIP_STATUS = ['draft', 'registration_open', 'ongoing', 'completed'] as const;
export type ChampionshipStatus = (typeof CHAMPIONSHIP_STATUS)[number];

export const TOURNAMENT_STATUS = ['draft', 'active', 'completed', 'cancelled'] as const;
export type TournamentStatus = (typeof TOURNAMENT_STATUS)[number];

export const TOURNAMENT_DISCIPLINE_STATUS = ['upcoming', 'ongoing', 'completed'] as const;
export type TournamentDisciplineStatus = (typeof TOURNAMENT_DISCIPLINE_STATUS)[number];

export const TEAM_STATUS = ['forming', 'submitted', 'approved', 'roster_locked'] as const;
export type TeamStatus = (typeof TEAM_STATUS)[number];

export const TEAM_MEMBER_ROLE = ['captain', 'vice_captain', 'player', 'substitute'] as const;
export type TeamMemberRole = (typeof TEAM_MEMBER_ROLE)[number];

export const FIXTURE_STATUS = [
  'scheduled', 'live', 'completed', 'postponed', 'cancelled', 'bye', 'walkover',
] as const;
export type FixtureStatus = (typeof FIXTURE_STATUS)[number];

export const SPONSOR_TIER = ['title', 'gold', 'silver', 'community'] as const;
export type SponsorTier = (typeof SPONSOR_TIER)[number];

export const GROUND_TYPE = ['court', 'field', 'pool', 'track', 'ring', 'table'] as const;
export type GroundType = (typeof GROUND_TYPE)[number];

export const ENTRY_TYPE = ['team', 'individual', 'doubles', 'relay'] as const;
export type EntryType = (typeof ENTRY_TYPE)[number];

export const ENROLLMENT_STATUS = ['pending', 'approved', 'rejected'] as const;
export type EnrollmentStatus = (typeof ENROLLMENT_STATUS)[number];

// A user's role within an organization (membership is many-to-many). owner/admin
// administer the org (teams, members, enrollment); captain leads a team; member /
// alumni are participants. Replaces the old global `account_type`.
export const ORGANIZATION_MEMBER_ROLE = ['owner', 'admin', 'captain', 'member', 'alumni'] as const;
export type OrganizationMemberRole = (typeof ORGANIZATION_MEMBER_ROLE)[number];

// The set of shells the UI can render. Every login is a `user`; `system` is
// reserved for platform super admins (is_super_admin). Capabilities are otherwise
// derived per championship (user_championship_roles / championship_officials) and
// per organization (organization_members).
export const APP_ROLE = ['system', 'user'] as const;
export type AppRole = (typeof APP_ROLE)[number];

// ---------- Notifications ----------
// type: how the notification was produced. 'manual' = pushed by an authorized
// user; the other two are auto-generated by lifecycle/approval hooks.
export const NOTIFICATION_TYPE = ['manual', 'event_lifecycle', 'enrollment_approved'] as const;
export type NotificationType = (typeof NOTIFICATION_TYPE)[number];

// audience: who may see the notification. 'all' = every championship-related user;
// 'organizations_captains' = organization owners/admins + team captains/vice-captains.
export const NOTIFICATION_AUDIENCE = ['all', 'organizations_captains'] as const;
export type NotificationAudience = (typeof NOTIFICATION_AUDIENCE)[number];

// The fixed set of emoji reactions recipients may toggle on a notification.
export const NOTIFICATION_REACTIONS = ['👍', '❤️', '🎉', '👏'] as const;
export type NotificationReaction = (typeof NOTIFICATION_REACTIONS)[number];

// Legal championship status transitions (enforced by the ChampionshipLifecycle domain service).
export const CHAMPIONSHIP_STATUS_TRANSITIONS: Record<ChampionshipStatus, ChampionshipStatus[]> = {
  draft: ['registration_open'],
  registration_open: ['ongoing', 'draft'],
  ongoing: ['completed'],
  completed: [],
};
