// Enum unions mirroring the DB CHECK constraints. Arrays double as <select> options.

export const CHAMPIONSHIP_STATUS = ['draft', 'registration_open', 'ongoing', 'completed'] as const;
export type ChampionshipStatus = (typeof CHAMPIONSHIP_STATUS)[number];

export const TOURNAMENT_STATUS = ['draft', 'active', 'completed', 'cancelled'] as const;
export type TournamentStatus = (typeof TOURNAMENT_STATUS)[number];

export const TOURNAMENT_DISCIPLINE_STATUS = ['upcoming', 'ongoing', 'completed'] as const;
export type TournamentDisciplineStatus = (typeof TOURNAMENT_DISCIPLINE_STATUS)[number];

export const TEAM_STATUS = ['forming', 'submitted', 'approved', 'roster_locked'] as const;
export type TeamStatus = (typeof TEAM_STATUS)[number];

export const TEAM_MEMBER_ROLE = ['captain', 'vice_captain', 'player', 'substitute'] as const;
export type TeamMemberRole = (typeof TEAM_MEMBER_ROLE)[number];

export const FIXTURE_STATUS = [
  'scheduled', 'live', 'completed', 'postponed', 'cancelled', 'bye', 'walkover',
] as const;
export type FixtureStatus = (typeof FIXTURE_STATUS)[number];

export const SPONSOR_TIER = ['title', 'gold', 'silver', 'community'] as const;
export type SponsorTier = (typeof SPONSOR_TIER)[number];

export const GROUND_TYPE = ['court', 'field', 'pool', 'track', 'ring', 'table'] as const;
export type GroundType = (typeof GROUND_TYPE)[number];

export const ENTRY_TYPE = ['team', 'individual', 'doubles', 'relay'] as const;
export type EntryType = (typeof ENTRY_TYPE)[number];

export const ENROLLMENT_STATUS = ['pending', 'approved', 'rejected'] as const;
export type EnrollmentStatus = (typeof ENROLLMENT_STATUS)[number];

// A user's role within an organization (membership is many-to-many). owner/admin
// administer the org (teams, members, enrollment); captain leads a team; member /
// alumni are participants. Replaces the old global `account_type`.
export const ORGANIZATION_MEMBER_ROLE = ['owner', 'admin', 'captain', 'member', 'alumni'] as const;
export type OrganizationMemberRole = (typeof ORGANIZATION_MEMBER_ROLE)[number];

// ---------- Organisation tiers ----------
// The tier an organization sits at. 'community' is the lightweight thing anyone can
// create (the only kind that existed before EOS); 'institution' is a *verified* org
// with the full workspace - claimed email domains, reports, certificates; 'personal'
// is a hidden one-person org for solo entrants and never appears in any directory.
// Promotion to 'institution' is a super-admin action, never self-service.
export const ORG_KIND = ['community', 'institution', 'personal'] as const;
export type OrgKind = (typeof ORG_KIND)[number];

// ---------- Auth tokens ----------
// What a single-use token authorises. 'otp' = a 6-digit sign-in code; the other two
// are placeholders for the flows that need real email delivery (module 02).
export const AUTH_TOKEN_KIND = ['otp', 'password_reset', 'invite'] as const;
export type AuthTokenKind = (typeof AUTH_TOKEN_KIND)[number];

// Public mailbox providers can never be claimed as an organisation's domain - the
// first org to claim gmail.com would otherwise capture every personal address on the
// platform. Checked when a domain is added, and again when sign-in resolves one.
export const PUBLIC_EMAIL_DOMAINS = [
  'gmail.com', 'googlemail.com', 'yahoo.com', 'yahoo.co.in', 'ymail.com',
  'outlook.com', 'hotmail.com', 'live.com', 'msn.com',
  'icloud.com', 'me.com', 'aol.com', 'proton.me', 'protonmail.com',
  'zoho.com', 'rediffmail.com', 'mail.com', 'gmx.com', 'yandex.com',
] as const;

// The methods a sign-in screen may offer. 'otp' is the default door in the
// email-first flow; 'password' stays available for existing/provisioned logins.
export const AUTH_METHOD = ['otp', 'password'] as const;
export type AuthMethod = (typeof AUTH_METHOD)[number];

// The set of shells the UI can render. Every login is a `user`; `system` is
// reserved for platform super admins (is_super_admin). Capabilities are otherwise
// derived per championship (user_championship_roles / championship_officials) and
// per organization (organization_members).
export const APP_ROLE = ['system', 'user'] as const;
export type AppRole = (typeof APP_ROLE)[number];

// ---------- Notifications ----------
// type: how the notification was produced. 'manual' = pushed by an authorized
// user; the rest are auto-generated by lifecycle/approval hooks. The org_join_*
// types belong to the organization-membership flow (no championship).
//
// The enrollment family distinguishes WHO the news is for, because that is what the
// feed's icon, and any future email digest or notification preference, has to key off:
//
//   enrollment_requested  someone applied; an organiser must decide
//   entry_submitted       an individual entered; an organiser must decide
//   enrollment_approved   YOU are in
//   enrollment_rejected   YOU are not
//   enrollment_joined     somebody else joined - news, not a task
//
// These were one type until 2026-08-16, which meant an organiser with a pending
// approval saw a green tick telling them it was already handled.
export const NOTIFICATION_TYPE = [
  'manual', 'event_lifecycle',
  'enrollment_requested', 'enrollment_approved', 'enrollment_rejected', 'enrollment_joined',
  'entry_submitted',
  'org_join_request', 'org_join_approved', 'org_join_declined',
  'org_invitation',
  // J4-E5 - three, not one: the validator's 'somebody is waiting on you' and the
  // claimant's 'you were turned down, here is why' are different messages.
  'claim_submitted', 'claim_approved', 'claim_rejected',
] as const;
export type NotificationType = (typeof NOTIFICATION_TYPE)[number];

// audience: who may see the notification. 'all' = every championship-related user;
// 'organizations_captains' = organization owners/admins + team captains/vice-captains;
// 'org_admins' = the owners/admins of the notification's organization_id (used for
// join requests). Direct-to-user notifications set target_user_id instead.
export const NOTIFICATION_AUDIENCE = ['all', 'organizations_captains', 'org_admins'] as const;
export type NotificationAudience = (typeof NOTIFICATION_AUDIENCE)[number];

// The fixed set of emoji reactions recipients may toggle on a notification.
export const NOTIFICATION_REACTIONS = ['👍', '❤️', '🎉', '👏'] as const;
export type NotificationReaction = (typeof NOTIFICATION_REACTIONS)[number];

// ---------- Standings ----------
// The scoring scheme used to turn completed fixtures into a points table. Resolved
// per discipline (see STANDINGS_RULE_SCOPE); the engine runs the matching strategy.
//   league_points - points per win/draw/loss (the classic league table; default).
//   placement     - knockout: points by how far a team advanced (winner, SF, …).
//   medal         - top-3 organizations in a discipline earn gold/silver/bronze points.
//   custom        - the organiser awards championship points per side, by hand, after
//                   each result on the Results page (no auto formula).
//   ranking       - ranking events (swimming/powerlifting/athletics): organiser sets the
//                   points for each finishing place (1st/2nd/3rd/…); the event console's
//                   final ranking awards them. No head-to-head fixtures.
export const STANDINGS_SCHEME = ['league_points', 'placement', 'medal', 'custom', 'ranking'] as const;
export type StandingsScheme = (typeof STANDINGS_SCHEME)[number];

// Ordered tiebreakers for the league_points scheme (applied left-to-right).
export const STANDINGS_TIEBREAKER = ['points', 'wins', 'lost', 'head_to_head', 'score_diff'] as const;
export type StandingsTiebreaker = (typeof STANDINGS_TIEBREAKER)[number];

// Where an editable scoring rule applies. Resolution is most-specific-wins:
// discipline → format → championship default → DEFAULT_STANDINGS_RULE.
export const STANDINGS_RULE_SCOPE = ['championship', 'format', 'discipline'] as const;
export type StandingsRuleScope = (typeof STANDINGS_RULE_SCOPE)[number];

// Where a materialized standings table is aggregated / shown. championship is the
// default view; tournament and sport are reachable via filters.
export const STANDINGS_AGG_SCOPE = ['championship', 'tournament', 'sport'] as const;
export type StandingsAggScope = (typeof STANDINGS_AGG_SCOPE)[number];

// Canonical knockout placements the placement scheme can award points to. Derived
// from the bracket round a team was eliminated in (or won, for `winner`).
export const STANDINGS_PLACEMENT = [
  'winner', 'runner_up', 'third_place', 'fourth_place', 'semi_finalist', 'quarter_finalist',
] as const;
export type StandingsPlacement = (typeof STANDINGS_PLACEMENT)[number];

// How a placement is written for a human - on a standings breakdown, on a
// certificate, and on a lifetime record that outlives this codebase. It lived in
// two web components with slightly different copy; achievements made a third
// copy one too many.
export const PLACEMENT_LABEL: Record<StandingsPlacement, string> = {
  winner: 'Winner',
  runner_up: 'Runner-up',
  third_place: 'Third place',
  fourth_place: 'Fourth place',
  semi_finalist: 'Semi-finalist',
  quarter_finalist: 'Quarter-finalist',
};

// ---------- Achievements & the lifetime record (J4-E2 / J4-E4) ----------

// What a lifetime timeline entry is. Lock-derived entries are always
// 'participation' or 'result' - one per person per verified fixture, with any
// medal/award carried as a chip. The remaining kinds belong to validated claims
// (J4-E5), which have no fixture behind them.
export const LIFETIME_ENTRY_KIND = [
  'participation', 'result', 'medal', 'award', 'record', 'selection',
] as const;
export type LifetimeEntryKind = (typeof LIFETIME_ENTRY_KIND)[number];

export const ACHIEVEMENT_KIND = [
  'medal', 'placement', 'record', 'selection', 'honour', 'award',
] as const;
export type AchievementKind = (typeof ACHIEVEMENT_KIND)[number];

export const MEDALS = ['gold', 'silver', 'bronze'] as const;
export type Medal = (typeof MEDALS)[number];

export const MEDAL_LABEL: Record<Medal, string> = { gold: 'Gold', silver: 'Silver', bronze: 'Bronze' };

// Where a record came from. 'locked_result' is the only one the lock writes;
// the others exist so a claim (J4-E5) and an import can never be mistaken for a
// result the platform itself verified.
export const RECORD_SOURCE = ['locked_result', 'validated_claim', 'migrated'] as const;
export type RecordSource = (typeof RECORD_SOURCE)[number];

// ---------- Demo requests ----------
// Triage state for a "Book a demo" lead captured from the public landing page.
// 'new' on capture; an admin moves it through contacted → scheduled → closed.
export const DEMO_REQUEST_STATUS = ['new', 'contacted', 'scheduled', 'closed'] as const;
export type DemoRequestStatus = (typeof DEMO_REQUEST_STATUS)[number];

// Self-described role a landing-page visitor picks in the demo form. Free-form on
// the server (stored as text); this list just drives the <select> options.
export const DEMO_REQUEST_ROLES = [
  'Sports Secretary', 'PE Teacher', 'Sports Authority', 'Club / Academy', 'Other',
] as const;
export type DemoRequestRole = (typeof DEMO_REQUEST_ROLES)[number];

// ---------- Feedback ----------
// Triage state for user feedback captured from the public pages + the in-app shell.
// 'new' on capture; an admin moves it through reviewing → resolved/closed.
export const FEEDBACK_STATUS = ['new', 'reviewing', 'resolved', 'closed'] as const;
export type FeedbackStatus = (typeof FEEDBACK_STATUS)[number];

// ---------- Championship type ----------
// What kind of event this is. Nullable in the DB: championships created before the
// question existed have no honest answer, and a backfilled guess would poison the
// filters and the reports that group by it.
//   multi_sport      - several sports, one meet (the annual championship)
//   inter_college    - across institutions
//   inter_programme  - inside one institution, between programmes/batches
//   single_sport     - one sport, run as a league or a cup
//   open             - anyone may enter, not tied to an institution
export const CHAMPIONSHIP_TYPE = [
  'multi_sport', 'inter_college', 'inter_programme', 'single_sport', 'open',
] as const;
export type ChampionshipType = (typeof CHAMPIONSHIP_TYPE)[number];

export const CHAMPIONSHIP_TYPE_LABELS: Record<ChampionshipType, string> = {
  multi_sport: 'Multi-sport',
  inter_college: 'Inter-college',
  inter_programme: 'Inter-programme',
  single_sport: 'Single sport',
  open: 'Open',
};

// ---------- Championship visibility ----------
// 'public' championships appear in Discover/Browse for everyone; 'private' ones are
// visible only to people already involved (organiser, official, enrolled/invited org
// members) and organizations join them by invitation only.
export const CHAMPIONSHIP_VISIBILITY = ['public', 'private'] as const;
export type ChampionshipVisibility = (typeof CHAMPIONSHIP_VISIBILITY)[number];

// ---------- Demo sandboxes ----------
// Lifecycle of a per-client demo environment. Busy states (seeding/resetting/
// deleting) run in a background job; ready/error are the resting states.
export const DEMO_SANDBOX_STATUS = ['seeding', 'ready', 'resetting', 'deleting', 'error'] as const;
export type DemoSandboxStatus = (typeof DEMO_SANDBOX_STATUS)[number];

// Sports pre-selected in the sandbox create form. Each must exist in the global
// sports catalog; the form lets the admin add/remove from the full catalog.
export const DEMO_DEFAULT_SPORTS = [
  'Badminton', 'Table Tennis', 'Football', 'Basketball', 'Cricket', 'Volleyball',
] as const;

// The four championship archetypes every sandbox contains, each frozen at a
// different lifecycle stage for the demo narrative.
export const DEMO_CHAMP_KINDS = ['college', 'school', 'corporate', 'public'] as const;
export type DemoChampKind = (typeof DEMO_CHAMP_KINDS)[number];

// Legal championship status transitions (enforced by the ChampionshipLifecycle domain service).
export const CHAMPIONSHIP_STATUS_TRANSITIONS: Record<ChampionshipStatus, ChampionshipStatus[]> = {
  draft: ['registration_open'],
  registration_open: ['ongoing', 'draft'],
  ongoing: ['completed'],
  completed: [],
};
