// Enum unions mirroring the DB CHECK constraints. Arrays double as <select> options.

export const CHAMPIONSHIP_STATUS = ['draft', 'registration_open', 'ongoing', 'completed'] as const;
export type ChampionshipStatus = (typeof CHAMPIONSHIP_STATUS)[number];

export const TOURNAMENT_STATUS = ['draft', 'active', 'completed', 'cancelled'] as const;
export type TournamentStatus = (typeof TOURNAMENT_STATUS)[number];

export const TOURNAMENT_DISCIPLINE_STATUS = ['upcoming', 'ongoing', 'completed'] as const;
export type TournamentDisciplineStatus = (typeof TOURNAMENT_DISCIPLINE_STATUS)[number];

export const TEAM_STATUS = ['forming', 'submitted', 'approved', 'roster_locked'] as const;
export type TeamStatus = (typeof TEAM_STATUS)[number];

export const TEAM_MEMBER_ROLE = ['captain', 'vice_captain', 'player', 'substitute'] as const;
export type TeamMemberRole = (typeof TEAM_MEMBER_ROLE)[number];

export const FIXTURE_STATUS = [
  'scheduled', 'live', 'completed', 'postponed', 'cancelled', 'bye', 'walkover',
] as const;
export type FixtureStatus = (typeof FIXTURE_STATUS)[number];

export const SPONSOR_TIER = ['title', 'gold', 'silver', 'community'] as const;
export type SponsorTier = (typeof SPONSOR_TIER)[number];

export const GROUND_TYPE = ['court', 'field', 'pool', 'track', 'ring', 'table'] as const;
export type GroundType = (typeof GROUND_TYPE)[number];

export const ENTRY_TYPE = ['team', 'individual', 'doubles', 'relay'] as const;
export type EntryType = (typeof ENTRY_TYPE)[number];

export const ENROLLMENT_STATUS = ['pending', 'approved', 'rejected'] as const;
export type EnrollmentStatus = (typeof ENROLLMENT_STATUS)[number];

// A user's role within an organization (membership is many-to-many). owner/admin
// administer the org (teams, members, enrollment); captain leads a team; member /
// alumni are participants. Replaces the old global `account_type`.
export const ORGANIZATION_MEMBER_ROLE = ['owner', 'admin', 'captain', 'member', 'alumni'] as const;
export type OrganizationMemberRole = (typeof ORGANIZATION_MEMBER_ROLE)[number];

// The set of shells the UI can render. Every login is a `user`; `system` is
// reserved for platform super admins (is_super_admin). Capabilities are otherwise
// derived per championship (user_championship_roles / championship_officials) and
// per organization (organization_members).
export const APP_ROLE = ['system', 'user'] as const;
export type AppRole = (typeof APP_ROLE)[number];

// ---------- Notifications ----------
// type: how the notification was produced. 'manual' = pushed by an authorized
// user; the rest are auto-generated by lifecycle/approval hooks. The org_join_*
// types belong to the organization-membership flow (no championship).
export const NOTIFICATION_TYPE = [
  'manual', 'event_lifecycle', 'enrollment_approved',
  'org_join_request', 'org_join_approved', 'org_join_declined',
] as const;
export type NotificationType = (typeof NOTIFICATION_TYPE)[number];

// audience: who may see the notification. 'all' = every championship-related user;
// 'organizations_captains' = organization owners/admins + team captains/vice-captains;
// 'org_admins' = the owners/admins of the notification's organization_id (used for
// join requests). Direct-to-user notifications set target_user_id instead.
export const NOTIFICATION_AUDIENCE = ['all', 'organizations_captains', 'org_admins'] as const;
export type NotificationAudience = (typeof NOTIFICATION_AUDIENCE)[number];

// The fixed set of emoji reactions recipients may toggle on a notification.
export const NOTIFICATION_REACTIONS = ['👍', '❤️', '🎉', '👏'] as const;
export type NotificationReaction = (typeof NOTIFICATION_REACTIONS)[number];

// ---------- Standings ----------
// The scoring scheme used to turn completed fixtures into a points table. Resolved
// per discipline (see STANDINGS_RULE_SCOPE); the engine runs the matching strategy.
//   league_points - points per win/draw/loss (the classic league table; default).
//   placement     - knockout: points by how far a team advanced (winner, SF, …).
//   medal         - top-3 organizations in a discipline earn gold/silver/bronze points.
//   custom        - the organiser awards championship points per side, by hand, after
//                   each result on the Results page (no auto formula).
export const STANDINGS_SCHEME = ['league_points', 'placement', 'medal', 'custom'] as const;
export type StandingsScheme = (typeof STANDINGS_SCHEME)[number];

// Ordered tiebreakers for the league_points scheme (applied left-to-right).
export const STANDINGS_TIEBREAKER = ['points', 'wins', 'lost', 'head_to_head', 'score_diff'] as const;
export type StandingsTiebreaker = (typeof STANDINGS_TIEBREAKER)[number];

// Where an editable scoring rule applies. Resolution is most-specific-wins:
// discipline → format → championship default → DEFAULT_STANDINGS_RULE.
export const STANDINGS_RULE_SCOPE = ['championship', 'format', 'discipline'] as const;
export type StandingsRuleScope = (typeof STANDINGS_RULE_SCOPE)[number];

// Where a materialized standings table is aggregated / shown. championship is the
// default view; tournament and sport are reachable via filters.
export const STANDINGS_AGG_SCOPE = ['championship', 'tournament', 'sport'] as const;
export type StandingsAggScope = (typeof STANDINGS_AGG_SCOPE)[number];

// Canonical knockout placements the placement scheme can award points to. Derived
// from the bracket round a team was eliminated in (or won, for `winner`).
export const STANDINGS_PLACEMENT = [
  'winner', 'runner_up', 'third_place', 'fourth_place', 'semi_finalist', 'quarter_finalist',
] as const;
export type StandingsPlacement = (typeof STANDINGS_PLACEMENT)[number];

// ---------- Demo requests ----------
// Triage state for a "Book a demo" lead captured from the public landing page.
// 'new' on capture; an admin moves it through contacted → scheduled → closed.
export const DEMO_REQUEST_STATUS = ['new', 'contacted', 'scheduled', 'closed'] as const;
export type DemoRequestStatus = (typeof DEMO_REQUEST_STATUS)[number];

// Self-described role a landing-page visitor picks in the demo form. Free-form on
// the server (stored as text); this list just drives the <select> options.
export const DEMO_REQUEST_ROLES = [
  'Sports Secretary', 'PE Teacher', 'Sports Authority', 'Club / Academy', 'Other',
] as const;
export type DemoRequestRole = (typeof DEMO_REQUEST_ROLES)[number];

// Legal championship status transitions (enforced by the ChampionshipLifecycle domain service).
export const CHAMPIONSHIP_STATUS_TRANSITIONS: Record<ChampionshipStatus, ChampionshipStatus[]> = {
  draft: ['registration_open'],
  registration_open: ['ongoing', 'draft'],
  ongoing: ['completed'],
  completed: [],
};
