#!/usr/bin/env node
/**
 * Assemble the one deployable site out of the two builds.
 *
 *   dist/          <- landing-page-v2/dist   (the marketing site, the root)
 *   dist/app/      <- apps/web/dist          (the product)
 *   dist/_redirects                          (generated below)
 *
 * Run after both builds; `netlify.toml` does exactly that. Publish `dist`.
 *
 * WHY TWO BUILDS AND NOT ONE APP: the marketing site defines its own CSS custom
 * properties, and its --sport-* accents collide by name with ~90 of apps/web's.
 * Vite makes every imported stylesheet global, so merging them into one bundle
 * needs the marketing CSS scoped under a root class first. Two builds, two
 * entry points, two bundles - no shared global scope, nothing to collide.
 */

import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(root, 'dist');
const LANDING = join(root, 'landing-page-v2', 'dist');
const WEB = join(root, 'apps', 'web', 'dist');

/* ---------------------------------------------------------------------------
   THE APP'S TOP-LEVEL ROUTE PREFIXES.

   Every one of these used to live at the domain root and now lives under /app,
   so every one needs a redirect or the move silently breaks live URLs. This list
   is the reason the move is safe, and it has to be kept in step with the
   top-level routes in apps/web/src/App.tsx.

   The four marked PUBLIC are the ones that genuinely cannot be allowed to break:
   they are handed out to people who have no account and no way to guess a new
   URL - and /verify is printed as a QR code on issued certificates, which cannot
   be reissued. A 301 keeps every one of them working, because QR scanners and
   browsers follow redirects.

   Checked against the marketing site's own routes (/, /features, /live-scoring,
   /reports, /solutions, /schools, /colleges, /corporate, /tournament-organizers,
   /players, /pricing, /demo, /contact): no overlap. If a future marketing page
   ever wants one of these names, the app wins - it has live URLs in the wild.
   --------------------------------------------------------------------------- */
const APP_PREFIXES = [
  'verify',        // PUBLIC - QR codes on printed certificates
  'c',             // PUBLIC - championship share links
  'p',             // PUBLIC - public player profiles
  'login',         // PUBLIC - bookmarked, and in every invite email
  'home',
  'profile',
  'organizations',
  'discover',
  'championships',
  'host',
  'officiating',
  'score',
  'platform',
  'notifications',
  'plans',
  'help',
  'design',
];

/** The publish-root _redirects file. Ordered: first match wins. */
function redirects() {
  const lines = [
    '# GENERATED by tools/assemble-site.mjs - do not edit in dist/.',
    '# Order matters: Netlify takes the first matching rule.',
    '#',
    '# Rules here are NOT forced (no "!"), so an actual file on disk always wins',
    '# first - /app/assets/index-abc.js serves the real asset rather than falling',
    '# into the SPA rewrite below.',
    '',
    '# 1. The app, at /app. Deep links inside it must serve its index.html so the',
    '#    client router can read the path.',
    '/app/*  /app/index.html  200',
    '',
    '# 2. Legacy root URLs -> /app. These paths were the app before the marketing',
    '#    site took the root; 301 so browsers, QR scanners and search engines all',
    '#    learn the new location and existing links keep working.',
  ];
  for (const p of APP_PREFIXES) {
    // Bare path AND sub-paths. `/verify` alone is a real page (type in a code),
    // and a lone `/verify/*` rule would not match it.
    lines.push(`/${p}  /app/${p}  301`);
    lines.push(`/${p}/*  /app/${p}/:splat  301`);
  }
  lines.push(
    '',
    '# 3. Everything else is the marketing site, which is also a client-side router.',
    '/*  /index.html  200',
    '',
  );
  return lines.join('\n');
}

function need(dir, what) {
  if (!existsSync(dir) || readdirSync(dir).length === 0) {
    console.error(`\n  x missing build: ${what}\n    expected files in ${dir}\n`);
    process.exit(1);
  }
}

need(LANDING, 'landing-page-v2 (npm --prefix landing-page-v2 run build)');
need(WEB, 'apps/web (npm run build --workspace @semp/web)');

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

// The marketing site becomes the root of the deploy.
cpSync(LANDING, OUT, { recursive: true });
// The app sits under /app. Vite built it with base '/app/', so its own asset
// references already point here.
cpSync(WEB, join(OUT, 'app'), { recursive: true });

// LAST, and deliberately so: this overwrites any _redirects either build carried
// into its dist. landing-page-v2's used to be a bare `/* /index.html 200`, which
// at the publish root would swallow /app entirely and serve the marketing 404
// page for the whole product. Writing ours last makes that unshadowable.
writeFileSync(join(OUT, '_redirects'), redirects(), 'utf8');

const n = APP_PREFIXES.length;
console.log(`\n  site assembled -> dist/`);
console.log(`    /            marketing site (landing-page-v2)`);
console.log(`    /app/        product (apps/web)`);
console.log(`    _redirects   ${n} legacy prefixes redirected to /app\n`);
